# Generated by Django 4.1.7 on 2023-02-27 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новое задание'), (2, 'Задание в процессе выполнения'), (3, 'Задание выполнено')], verbose_name='статус')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_done', models.DateTimeField(blank=True, null=True, verbose_name='дата выполнения задания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
                'ordering': ('date_create',),
            },
        ),
    ]
