# Generated by Django 4.1.7 on 2023-02-28 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'кузов',
                'verbose_name_plural': 'кузова',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'марка',
                'verbose_name_plural': 'марка',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'двигатель',
                'verbose_name_plural': 'двигатель',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_manufacture', models.PositiveSmallIntegerField(default=0, verbose_name='год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('capacity', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='объем двигателя')),
                ('transmission', models.PositiveSmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'типтроник'), (4, 'вариатор'), (5, 'робот')], verbose_name='коробка передач')),
                ('drive', models.PositiveSmallIntegerField(choices=[(1, 'передний привод'), (2, 'задний привод'), (3, 'полный привод')], verbose_name='привод')),
                ('wheel', models.PositiveSmallIntegerField(choices=[(1, 'слева'), (2, 'справа')], verbose_name='руль')),
                ('cleared_kz', models.BooleanField(default=False, verbose_name='растаможен в Казахстане')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('date_public', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='изображение')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.body', verbose_name='кузов')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.brand', verbose_name='марка')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.city', verbose_name='город')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.engine', verbose_name='двигатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Автомашина',
                'verbose_name_plural': 'Автомашины',
                'ordering': ('date_create', 'date_public'),
            },
        ),
    ]
